### ISSUE TITLE
shap.plot.dependence.color doesn't handle missing well

### ISSUE THREAD

**Issue by MatticeV** [liuyanguu/SHAPforxgboost#1]
When the input for x has missing values and smooth = TRUE it doesn't draw the smoothed line, without a na.rm=TRUE option.

**Comment by liuyanguu** [comment]
Sorry I am late to the party, I did not get an email notification because I forgot to watch the repo. When the x has missing values they will be removed automatically, there will be a warning but shouldn't be an error. 
The warning looks like: 
```
Warning messages:
1: Removed 50 rows containing non-finite values (stat_smooth). 
```
Not sure if I understand your question correctly, and I wish it has been solved by now.
