### ISSUE TITLE
What is n_groups in the force plot?

### ISSUE THREAD

**Issue by MJimitater** [liuyanguu/SHAPforxgboost#25]
Just a matter of understanding: what does `n_groups` stand for in the force plot creation?

e.g.
```
# choose to show top 4 features by setting `top_n = 4`, set 6 clustering groups.  
plot_data <- shap.prep.stack.data(shap_contrib = shap_values$shap_score, top_n = 4, n_groups = 6)
```

In the example code they are defined as clustering groups, does that mean that the force plot is somehow divided up into 6 blocks?

**Comment by liuyanguu** [comment]
It is the number of clustering groups to build into the dataset.
It is used [here](https://github.com/liuyanguu/SHAPforxgboost/blob/9cb234164dea8e0c618e7d67bf556365d6e64668/R/SHAP_funcs.R#L635) in the function. 
```
library(SHAPforxgboost)
plot_data <- shap.prep.stack.data(shap_contrib = shap_values_iris,
                                  n_groups = 4)
table(plot_data$group)
```

When plotting, there is an option to zoom in on one of the groups:
```
shap.plot.force_plot(plot_data,  zoom_in_group = 2) # zoom in the 2nd group 
```
The observations are indeed sorted by clusters but this is not always obvious on the plot --- you may not see a clear grouping of the observations since the clusters are not necessarily so different from each other.

**Comment by MJimitater** [comment]
Thank you @liuyanguu for always replying quickly and helpfully! Great explanation, thank you! And great package, I love!
BTW, perhaps a Discussion option (a tab that can be somehow activated in GitHub) is useful. Cheers
