### ISSUE TITLE
regression stats to `shap.plot.dependence`?

### ISSUE THREAD

**Issue by aruberuku** [liuyanguu/SHAPforxgboost#7]
Dear Colleague,

You hard work is very much appreciated, as is your kind attention.

`shap.plot.dependence` is important validating the output of the SHAP model.
The `histogram` option is very useful for this, as is the `smooth` option.
However, the latter almost demands that the linear equation and R-squared be shown.

**Would it be possible to implement as an option in `shap.plot.dependence`?**

There is some easy code that enables this, found here:
https://gist.github.com/kdauria/524eade46135f6348140

And here is an example of it being used in practice, with output below:
`library(devtools)
source_gist("524eade46135f6348140")
df = data.frame(x = c(1:100))
df$y = 2 + 5 * df$x + rnorm(100, sd = 40)
df$class = rep(1:2,50)
ggplot(data = df, aes(x = x, y = y, label=y)) +
  stat_smooth_func(geom="text",method="lm",hjust=0,parse=TRUE) +
  geom_smooth(method="lm",se=FALSE) +
  geom_point() + facet_wrap(~class)`

![image](https://user-images.githubusercontent.com/18650337/80359504-34202480-887e-11ea-9275-7a3aebab4336.png)

Thanks in advance!

**Comment by liuyanguu** [comment]
Very cool. I will take a look! Many thanks

**Comment by liuyanguu** [comment]
Now in the latest version (0.0.4) there is an option to show Pearson correlation which is basically 
```
plot1 <- plot1 + ggpubr::stat_cor(method = "pearson")
```
The default smooth line uses `loess` since most relationships are not linear. But you can make it linear by adding the `geom_smooth` yourself since the output is ggplot2 object (please turn `add_hist` off otherwise it is no longer ggplot2 object) 
```
shap.plot.dependence(data_long = shap_long_iris, x="Petal.Length",
                     add_hist = FALSE, smooth = FALSE, add_stat_cor = TRUE) + 
  ggplot2::geom_smooth(method = 'lm', color = 'red', size = 0.4, se = F)
```
![sample2](https://user-images.githubusercontent.com/11966330/82811889-cc023580-9e5f-11ea-89d1-02f6376d0d81.JPG)

the default:
```
shap.plot.dependence(data_long = shap_long_iris, x="Petal.Length",
                     add_hist = TRUE, add_stat_cor = TRUE)
```
![sample1](https://user-images.githubusercontent.com/11966330/82811967-f5bb5c80-9e5f-11ea-908d-142f3745f30e.JPG)

**Comment by aruberuku** [comment]
This is amazing. Thank you once again for the quick and responsive turn-around. Excellent progress being made all about. Cheers!
